name:                prog-in-haskell
version:             0.1.0.0
github:              "timeflieslikeanarrow/prog-in-haskell"
license:             BSD3
author:              "Jian Shi"
maintainer:          "timeflieslikeanarrow001@gmail.com"
copyright:           "2021 Jian Shi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/timeflieslikeanarrow/prog-in-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  prog-in-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prog-in-haskell

tests:
  prog-in-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - prog-in-haskell
